name: Update readme

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * 1'   # Monday ~14:37 AEDT
    - cron: '12 21 * * 2'  # Wednesday ~08:12 AEDT
    - cron: '51 8 * * 3'   # Wednesday ~19:51 AEDT
    - cron: '23 0 * * 4'   # Thursday ~11:23 AEDT
    - cron: '45 5 * * 5'   # Friday ~16:45 AEDT
    - cron: '8 19 * * 6'   # Sunday ~06:08 AEDT
    - cron: '33 11 * * 0'  # Sunday ~22:33 AEDT

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install github-readme-terminal python-dotenv pillow

      - name: Run script
        run: python generate_terminal_gif.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update readme
        run: |
          git add README.md output.gif
          git -c "user.name=bot" -c "user.email=bot@github.com" commit -m "Automatically updated on $(TZ='Australia/Melbourne' date)"
          git push
